version: '3.8'

services:
  db:
    build:
      context: ./db
    container_name: custom-postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: appointmentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/pgsql/15/data
    networks:
      - back-network

  app1:
    build: .
    container_name: app1
    expose:
      - "8999"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=appointmentdb
    depends_on:
      - db
    networks:
      - back-network

  app2:
    build: .
    container_name: app2
    expose:
      - "8999"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=appointmentdb
    depends_on:
      - db
    networks:
      - back-network

  haproxy:
    image: haproxy:2.8
    container_name: haproxy
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - app1
      - app2
    networks:
      - front-network
      - back-network

volumes:
  pgdata:

networks:
  front-network:
  back-network:
