services:
  db:
    build:
      context: ./db
    container_name: custom-postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: appointmentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgresql/data
    networks:
      - back-network

  app1:
    build:
      context: ./web
    container_name: app1
    expose:
      - "8999"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=appointmentdb
    depends_on:
      - db
    networks:
      - back-network

  app2:
    build:
      context: ./web
    container_name: app2
    expose:
      - "8999"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=appointmentdb
    depends_on:
      - db
    networks:
      - back-network

  haproxy:
    build: ./haproxy
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
    networks:
      - front-network
      - back-network

volumes:
  pgdata:


networks:
  front-network:
  back-network:
