services:
  db:
    build:
      context: ./db
    container_name: custom-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: appointmentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/pgsql/15/data
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8999:8999"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=appointmentdb
    depends_on:
      - db
    networks:
      - app-network  

volumes:
  pgdata:

networks:
  app-network:
